---
- name: Update and secure ubuntu servers
  hosts: localhost
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Install UFW and fail2ban
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ufw
          - fail2ban

    - name: Allow SSH, HTTP, and HTTPS through the firewall
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '22'    # SSH
        - '80'    # HTTP
        - '443'   # HTTPS

    - name: Enable firewall
      community.general.ufw:
        state: enabled

    - name: Enable fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true
...
